### ISSUE TITLE
Security question field is posted in the profile however the security question itself isn’t there

### ISSUE THREAD

**Issue by ranashehata** [SEGUC17/Replica-meanTech#15]
Severity : low
reported by: Rana AbdElAziz
description: When the user opens his profile, there is a security question field,however, the question itself is not displayed
Steps to reproduce this issue:
1)log in as a user
Expected result: either a)the field should not have been available from the start (to provide more security)
or b) the security question should have been displayed

**Comment by syrinehamza** [comment]
no the question is crucial to be able to reset the password
and it is not displayed when reset password for more security, if you forgot your question that's a problem, for example with the mail your mail is not displayed automatically, you have to remember it, same for the question.
