### ISSUE TITLE
URLs in registration form does't allow format www.xxxx.com

### ISSUE THREAD

**Issue by bassant97** [SEGUC17/Replica-meanTech#23]
1- Severity : low
2- Reported By : Bassant
3- Description : URL in registration form must be in a format xx://xx only even if it not valid url , it accepts it 
4- Steps to reproduce the issue : 
1) Subscribe company/user
2) validate all accepted formats for URL and make sure it valid URL
3) Fill rest of form
4) click sign up
5- Expected Result : when writing a valid url in a format of www.xxx.com it should accept it

**Comment by syrinehamza** [comment]
yes because URLs format is http://www.xxx.com not www.xxx.com only
