### ISSUE TITLE
Please choose another username

### ISSUE THREAD

**Issue by mohamednawzaad** [SEGUC17/Replica-meanTech#30]
Severity: High
Reported by : Mohamed Nawzad

3- Description
Error "Please choose another username" while signing up, it happend with random names as well

4-steps to reproduce the issue:
1- press subscribe
2-select user/company
3-press sign up  then error randomly appears sometimes called "please choose another name"

5- Expected results
The user should get registered successfully if all the info is correct.

**Comment by syrinehamza** [comment]
same as #11
