### ISSUE TITLE
Admin can answer the question but the user will not know

### ISSUE THREAD

**Issue by mohamednawzaad** [SEGUC17/Replica-meanTech#35]
Severity: High
Reported by : Mohamed Nawzad

3- Description
Admin can answer the questions however the user will not be notified and the user cant view the questions or answers while logged in.

4-steps to reproduce the issue:
1- fill in the username and password and then press login
2-press "new"
3-press Ask question
4- write the question the press post a question
5- then how do you find the question and the answer?

5- Expected results
The user should get post and view the questions.

**Comment by syrinehamza** [comment]
same as #2
