### ISSUE TITLE
Create account without email vertification

### ISSUE THREAD

**Issue by mohamednawzaad** [SEGUC17/Replica-meanTech#36]
Severity: High
Reported by : Mohamed Nawzad

3- Description
you can login with account you created without waiting for vertification

4-steps to reproduce the issue:
1- press subscribe
2-select user/company
3- fill in the information
4-press sign up 
5- go the home page and login

5- Expected results
the account should not be able to login unless it is verified.

**Comment by syrinehamza** [comment]
the client doesn't need to wait for a verification
the company cannot log in if it is not verified by the admin
