### ISSUE TITLE
you dont receive email vertification

### ISSUE THREAD

**Issue by mohamednawzaad** [SEGUC17/Replica-meanTech#37]
Severity: High
Reported by : Mohamed Nawzad

3- Description
you dont get the verification email

4-steps to reproduce the issue:
1- press subscribe
2-select user/company
3- fill in the information
4-press sign up 
5- check your email

5- Expected results
you should receive a verification email to complete the subscription procesess

**Comment by syrinehamza** [comment]
you're not supposed to receive an email but wait for the acceptance of the admin
