### ISSUE TITLE
Email is not used

### ISSUE THREAD

**Issue by MohamedNassefSelim** [SEGUC17/Replica-meanTech#41]
Severity: medium 
Reported by: Mohamed Amr Nassef 
Description: Email is not used neither in verification or in resetting password.It's just entered for nothing Steps to re-produce the issue: For every registered company ,  an email to be sent to the company to verify their account.
Expected result: All companies will be verified , and resetting passwords will be more secured.

**Comment by syrinehamza** [comment]
the verification is done by the admin i swear to God.
and the email is useful if anyone wants to contact this person by mail, well, he can.
